version: '3'

services:
  db_admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 30001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=stud@mospolytech.ru
      - PGADMIN_DEFAULT_PASSWORD=stud
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db:db-lesson
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=realtor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  pgadmin-data:
